# Generated by Django 5.0.6 on 2024-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_borrowinfo_uname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowinfo",
            name="return_date",
            field=models.DateTimeField(null=True, verbose_name="归还日期"),
        ),
    ]
